name: Docker

on:
 workflow_dispatch:
 push:
    branches:
      - main # default branch
    paths:
      - /*.py
      - locale/**
      - Dockerfile
      - .github/workflows/docker.yml

jobs:
  Ghcr:
    name: Publish to ghcr.io
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3.8.0
      - name: Login
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build & Push
        uses: docker/build-push-action@v6.11.0
        with:
          context: .
          push: true
          tags: ghcr.io/${{github.repository_owner}}/tgkb_bot:latest
          platforms: linux/amd64,linux/arm64
          cache-from: type=registry,ref=ghcr.io/${{github.repository_owner}}/tgkb_bot:latest
          cache-to: type=inline
